#!/bin/bash


export APPIMAGE_UUID=a369f900-1b93-4164-9285-f26fdad1dfba
export SYSTEM_INTERP=/lib64/ld-linux-x86-64.so.2
export APPDIR_INTERP=${APPDIR}/scrcpy/usr/lib/ld-linux-x86-64.so.2
export RUNTIME_INTERP=/tmp/appimage-a369f900-1b93-4164-9285-f26fdad1dfba-ld-linux.so.2
export EXEC_PATH="${APPDIR}/scrcpy/usr/bin/scrcpy"

export APPDIR_LIBRARY_PATH=$APPDIR/usr/lib
export LIBC_LIBRARY_PATH=$APPDIR/usr/lib
export APPDIR_LIBC_VERSION=2.35
export LD_PRELOAD=${APPDIR}/scrcpy/libapprun_hooks.so
"${APPDIR}/scrcpy/AppRun" "$@" 
