#!/usr/bin/env python3
COPYRIGHT = \
    """
GUISCRCPY by srevinsaju
Get it on : https://github.com/srevinsaju/guiscrcpy
Licensed under GNU Public License

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from os import path

this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

RAW_VERSION = "3.7"
PACKAGE_DIR = {
    'guiscrcpy': [
        '*', '*.*', 'resources/*', 'ui/*', 'lib/*', 'platform/*',
        'theme/*', 'ux/*', 'network/*', 'settings/*',
        'install/*', 'platform/windows_tools/*', 'ui/icons/*', 'ui/fonts/*', 'ui/rsrc/*', 'ui/ui/*'
    ]
}

CONSOLE_SCRIPTS = {
    'console_scripts': [
        'guiscrcpy = guiscrcpy.launcher:bootstrap',
    ]
}


def gen_version():
    """
    Generates a version from the available git repositories
    If git repository is not valid, fallback to __version__
    :return:
    """
    import git
    repo = git.Repo(search_parent_directories=True)
    sha = repo.head.object.hexsha
    ver = repo.git.describe("--tags")
    raw_version = ver.split('-')
    if len(raw_version) == 1:
        # Stable Release
        v = "{}".format(raw_version[0])
    elif len(raw_version) == 2:
        # Release Candidate
        v = "{major}.post{minor}".format(
            major=raw_version[0], minor=raw_version[1])
    else:
        # Revision Dev
        v = "{major}.post{minor}.dev".format(
            major=raw_version[0], minor=raw_version[1])

    return v


try:
    v = gen_version()
except Exception as e:
    print("WARNING: {}".format(e))
    v = f"{RAW_VERSION}.x.src.dev"

# Attach requirements

setupfile = \
    '''#!/usr/bin/env python3
"""
{COPYRIGHT}
"""

from setuptools import setup
import platform 

requirements = ['PyQt5==5.14.2', 'pynput']
if platform.system() == 'Windows':
    requirements.extend(['pywin32', 'psutil'])
elif platform.system() == 'Linux':
    requirements.extend(['fonttools', 'psutil'])



setup(
    name='guiscrcpy',
    version='{version}',
    description='An Open Source - Fast - Android Screen Mirroring system.',
    long_description="""{long_description}""",
    long_description_content_type='text/markdown',
    license='GPL v3',
    author='srevinsaju',
    author_email="srevin03@gmail.com",
    packages=['guiscrcpy'],
    data_files = [
        ('share/applications', ['guiscrcpy.desktop'] )
    ],
    url="https://srevinsaju.github.io/guiscrcpy",
    download_url="https://github.com/srevinsaju/guiscrcpy/archive/master.zip",
    package_data={package_data},
    include_package_data=True,
    install_requires=requirements,
    scripts=["scripts/guiscrcpy", "scripts/guiscrcpy-mapper"],
    entry_points={entry_points},
    classifiers=['Operating System :: OS Independent',
                 'Programming Language :: Python :: 3.7',
                 'Programming Language :: Python :: 3.6',
                 'Programming Language :: Python :: 3.8',
                 'Operating System :: MacOS :: MacOS X',
                 'Operating System :: Microsoft :: Windows',
                 'Operating System :: POSIX',
                 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)'],
)

'''

VERSION_FILE = \
    '''#!/usr/bin/env python3
"""
{COPYRIGHT}
"""

VERSION = '{version}'
'''

# Create a new setup.py with all the information raw.
# this was because GitPython created a lot of problems
# hardcoding the information before each release, solved the problem

with open("setup.py", 'w') as w:
    w.write(setupfile.format(
        COPYRIGHT=COPYRIGHT,
        version=v,
        package_data=PACKAGE_DIR,
        entry_points=CONSOLE_SCRIPTS,
        long_description=long_description,
    ))

with open("guiscrcpy/version.py", 'w') as w:
    w.write(VERSION_FILE.format(
        COPYRIGHT=COPYRIGHT,
        version=v,
    ))

print("Setup filename generated.")
print("GUISCRCPY >> VERSION : {}".format(v))
