# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolkit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 137)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rsrc/android_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.fullscreenUI = QtWidgets.QPushButton(Dialog)
        self.fullscreenUI.setGeometry(QtCore.QRect(10, 40, 31, 25))
        self.fullscreenUI.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rsrc/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fullscreenUI.setIcon(icon1)
        self.fullscreenUI.setObjectName("fullscreenUI")
        self.clipD2PC = QtWidgets.QPushButton(Dialog)
        self.clipD2PC.setGeometry(QtCore.QRect(50, 40, 31, 25))
        self.clipD2PC.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("rsrc/clip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipD2PC.setIcon(icon2)
        self.clipD2PC.setObjectName("clipD2PC")
        self.powerUI = QtWidgets.QPushButton(Dialog)
        self.powerUI.setGeometry(QtCore.QRect(10, 70, 231, 25))
        self.powerUI.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("rsrc/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerUI.setIcon(icon3)
        self.powerUI.setObjectName("powerUI")
        self.appswi = QtWidgets.QPushButton(Dialog)
        self.appswi.setGeometry(QtCore.QRect(170, 40, 31, 25))
        self.appswi.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("rsrc/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appswi.setIcon(icon4)
        self.appswi.setObjectName("appswi")
        self.menuUI = QtWidgets.QPushButton(Dialog)
        self.menuUI.setGeometry(QtCore.QRect(10, 100, 71, 25))
        self.menuUI.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("rsrc/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuUI.setIcon(icon5)
        self.menuUI.setObjectName("menuUI")
        self.vup = QtWidgets.QPushButton(Dialog)
        self.vup.setEnabled(False)
        self.vup.setGeometry(QtCore.QRect(210, 10, 31, 25))
        self.vup.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("rsrc/volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vup.setIcon(icon6)
        self.vup.setObjectName("vup")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(170, 100, 71, 25))
        self.back.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("rsrc/left-arrow-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon7)
        self.back.setObjectName("back")
        self.home = QtWidgets.QPushButton(Dialog)
        self.home.setGeometry(QtCore.QRect(90, 100, 71, 25))
        self.home.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("rsrc/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon8)
        self.home.setObjectName("home")
        self.vdown = QtWidgets.QPushButton(Dialog)
        self.vdown.setEnabled(False)
        self.vdown.setGeometry(QtCore.QRect(210, 40, 31, 25))
        self.vdown.setText("")
        self.vdown.setIcon(icon6)
        self.vdown.setObjectName("vdown")
        self.screenfreeze = QtWidgets.QPushButton(Dialog)
        self.screenfreeze.setEnabled(False)
        self.screenfreeze.setGeometry(QtCore.QRect(10, 10, 191, 25))
        self.screenfreeze.setObjectName("screenfreeze")
        self.clipPC2D = QtWidgets.QPushButton(Dialog)
        self.clipPC2D.setGeometry(QtCore.QRect(90, 40, 31, 25))
        self.clipPC2D.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("rsrc/credit-card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipPC2D.setIcon(icon9)
        self.clipPC2D.setObjectName("clipPC2D")
        self.notif_pull = QtWidgets.QPushButton(Dialog)
        self.notif_pull.setGeometry(QtCore.QRect(130, 40, 31, 25))
        self.notif_pull.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("rsrc/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notif_pull.setIcon(icon10)
        self.notif_pull.setObjectName("notif_pull")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GUI ScrcPy - Toolkit"))
        self.fullscreenUI.setToolTip(_translate("Dialog", "Fullscreen"))
        self.clipD2PC.setToolTip(_translate("Dialog", "Copy device clipbioard to PC"))
        self.powerUI.setToolTip(_translate("Dialog", "Power on/off"))
        self.appswi.setToolTip(_translate("Dialog", "press the APP_SWITCH button"))
        self.menuUI.setToolTip(_translate("Dialog", "Menu key"))
        self.vup.setToolTip(_translate("Dialog", "Volume Up"))
        self.back.setToolTip(_translate("Dialog", "Back key"))
        self.home.setToolTip(_translate("Dialog", "Home key"))
        self.screenfreeze.setText(_translate("Dialog", "Screen Freeze"))
        self.clipPC2D.setToolTip(_translate("Dialog", "Copy PC clipboard to Device"))
        self.notif_pull.setToolTip(_translate("Dialog", "Expand notification panel"))
