# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolkit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(30, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rsrc/android_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)

        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 31, 377))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.screenfreeze = QtWidgets.QPushButton(self.layoutWidget)
        self.screenfreeze.setEnabled(True)
        self.screenfreeze.setMouseTracking(True)
        self.screenfreeze.setTabletTracking(True)
        self.screenfreeze.setAutoFillBackground(False)
        self.screenfreeze.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.screenfreeze.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rsrc/cancel-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenfreeze.setIcon(icon1)
        self.screenfreeze.setObjectName("screenfreeze")
        self.verticalLayout.addWidget(self.screenfreeze)
        self.fullscreenUI = QtWidgets.QPushButton(self.layoutWidget)
        self.fullscreenUI.setEnabled(True)
        self.fullscreenUI.setMouseTracking(True)
        self.fullscreenUI.setTabletTracking(True)
        self.fullscreenUI.setAutoFillBackground(False)
        self.fullscreenUI.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.fullscreenUI.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("rsrc/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fullscreenUI.setIcon(icon2)
        self.fullscreenUI.setObjectName("fullscreenUI")
        self.verticalLayout.addWidget(self.fullscreenUI)
        self.notif_pull = QtWidgets.QPushButton(self.layoutWidget)
        self.notif_pull.setEnabled(True)
        self.notif_pull.setMouseTracking(True)
        self.notif_pull.setTabletTracking(True)
        self.notif_pull.setAutoFillBackground(False)
        self.notif_pull.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.notif_pull.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("rsrc/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notif_pull.setIcon(icon3)
        self.notif_pull.setObjectName("notif_pull")
        self.verticalLayout.addWidget(self.notif_pull)
        self.notif_collapse = QtWidgets.QPushButton(self.layoutWidget)
        self.notif_collapse.setEnabled(True)
        self.notif_collapse.setMouseTracking(True)
        self.notif_collapse.setTabletTracking(True)
        self.notif_collapse.setAutoFillBackground(False)
        self.notif_collapse.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.notif_collapse.setText("")
        self.notif_collapse.setIcon(icon3)
        self.notif_collapse.setObjectName("notif_collapse")
        self.verticalLayout.addWidget(self.notif_collapse)
        self.clipD2PC = QtWidgets.QPushButton(self.layoutWidget)
        self.clipD2PC.setEnabled(True)
        self.clipD2PC.setMouseTracking(True)
        self.clipD2PC.setTabletTracking(True)
        self.clipD2PC.setAutoFillBackground(False)
        self.clipD2PC.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.clipD2PC.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("rsrc/clip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipD2PC.setIcon(icon4)
        self.clipD2PC.setObjectName("clipD2PC")
        self.verticalLayout.addWidget(self.clipD2PC)
        self.vup = QtWidgets.QPushButton(self.layoutWidget)
        self.vup.setEnabled(True)
        self.vup.setMouseTracking(True)
        self.vup.setTabletTracking(True)
        self.vup.setAutoFillBackground(False)
        self.vup.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.vup.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("rsrc/volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vup.setIcon(icon5)
        self.vup.setObjectName("vup")
        self.verticalLayout.addWidget(self.vup)
        self.vdown = QtWidgets.QPushButton(self.layoutWidget)
        self.vdown.setEnabled(True)
        self.vdown.setMouseTracking(True)
        self.vdown.setTabletTracking(True)
        self.vdown.setAutoFillBackground(False)
        self.vdown.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.vdown.setText("")
        self.vdown.setIcon(icon5)
        self.vdown.setObjectName("vdown")
        self.verticalLayout.addWidget(self.vdown)
        self.powerUI = QtWidgets.QPushButton(self.layoutWidget)
        self.powerUI.setEnabled(True)
        self.powerUI.setMouseTracking(True)
        self.powerUI.setTabletTracking(True)
        self.powerUI.setAutoFillBackground(False)
        self.powerUI.setStyleSheet("background-color: rgb(255,255,255);\n"
"")
        self.powerUI.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("rsrc/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerUI.setIcon(icon6)
        self.powerUI.setCheckable(False)
        self.powerUI.setObjectName("powerUI")
        self.verticalLayout.addWidget(self.powerUI)
        self.home = QtWidgets.QPushButton(self.layoutWidget)
        self.home.setEnabled(True)
        self.home.setMouseTracking(True)
        self.home.setTabletTracking(True)
        self.home.setAutoFillBackground(False)
        self.home.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.home.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("rsrc/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon7)
        self.home.setObjectName("home")
        self.verticalLayout.addWidget(self.home)
        self.back = QtWidgets.QPushButton(self.layoutWidget)
        self.back.setEnabled(True)
        self.back.setMouseTracking(True)
        self.back.setTabletTracking(True)
        self.back.setAutoFillBackground(False)
        self.back.setStyleSheet("background-color: rgb(255,255,255);\n"
"")
        self.back.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("rsrc/left-arrow-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon8)
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)
        self.menuUI = QtWidgets.QPushButton(self.layoutWidget)
        self.menuUI.setEnabled(True)
        self.menuUI.setMouseTracking(True)
        self.menuUI.setTabletTracking(True)
        self.menuUI.setAutoFillBackground(False)
        self.menuUI.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.menuUI.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("rsrc/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuUI.setIcon(icon9)
        self.menuUI.setObjectName("menuUI")
        self.verticalLayout.addWidget(self.menuUI)
        self.appswi = QtWidgets.QPushButton(self.layoutWidget)
        self.appswi.setEnabled(True)
        self.appswi.setMouseTracking(True)
        self.appswi.setTabletTracking(True)
        self.appswi.setAutoFillBackground(False)
        self.appswi.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.appswi.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("rsrc/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appswi.setIcon(icon10)
        self.appswi.setObjectName("appswi")
        self.verticalLayout.addWidget(self.appswi)
        self.clipPC2D = QtWidgets.QPushButton(self.layoutWidget)
        self.clipPC2D.setEnabled(True)
        self.clipPC2D.setMouseTracking(True)
        self.clipPC2D.setTabletTracking(True)
        self.clipPC2D.setAutoFillBackground(False)
        self.clipPC2D.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.clipPC2D.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("rsrc/credit-card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipPC2D.setIcon(icon11)
        self.clipPC2D.setObjectName("clipPC2D")
        self.verticalLayout.addWidget(self.clipPC2D)
        self.pinchinUI = QtWidgets.QPushButton(self.layoutWidget)
        self.pinchinUI.setEnabled(False)
        self.pinchinUI.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("rsrc/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pinchinUI.setIcon(icon12)
        self.pinchinUI.setObjectName("pinchinUI")
        self.verticalLayout.addWidget(self.pinchinUI)
        self.pinchoutUI = QtWidgets.QPushButton(self.layoutWidget)
        self.pinchoutUI.setEnabled(False)
        self.pinchoutUI.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("rsrc/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pinchoutUI.setIcon(icon13)
        self.pinchoutUI.setObjectName("pinchoutUI")
        self.verticalLayout.addWidget(self.pinchoutUI)
        self.potraitUI = QtWidgets.QPushButton(self.layoutWidget)
        self.potraitUI.setEnabled(True)
        self.potraitUI.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("rsrc/potrait.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.potraitUI.setIcon(icon14)
        self.potraitUI.setObjectName("potraitUI")
        self.verticalLayout.addWidget(self.potraitUI)
        self.landscapeUI = QtWidgets.QPushButton(self.layoutWidget)
        self.landscapeUI.setEnabled(True)
        self.landscapeUI.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("rsrc/landscape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.landscapeUI.setIcon(icon15)
        self.landscapeUI.setObjectName("landscapeUI")
        self.verticalLayout.addWidget(self.landscapeUI)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GUI ScrcPy - Toolkit"))
        self.fullscreenUI.setToolTip(_translate("Dialog", "Fullscreen"))
        self.notif_pull.setToolTip(_translate("Dialog", "Expand notification panel"))
        self.notif_collapse.setToolTip(_translate("Dialog", "Expand notification panel"))
        self.clipD2PC.setToolTip(_translate("Dialog", "Copy device clipbioard to PC"))
        self.vup.setToolTip(_translate("Dialog", "Volume Up"))
        self.powerUI.setToolTip(_translate("Dialog", "Power on/off"))
        self.home.setToolTip(_translate("Dialog", "Home key"))
        self.back.setToolTip(_translate("Dialog", "Back key"))
        self.menuUI.setToolTip(_translate("Dialog", "Menu key"))
        self.appswi.setToolTip(_translate("Dialog", "press the APP_SWITCH button"))
        self.clipPC2D.setToolTip(_translate("Dialog", "Copy PC clipboard to Device"))
        self.pinchinUI.setToolTip(_translate("Dialog", "Pinch in the screen"))
        self.pinchoutUI.setToolTip(_translate("Dialog", "Pinch out in the screen"))


