#!/usr/bin/python3
# -*- coding: utf-8 -*-
import guiscrcpy
patz = list(guiscrcpy.__path__)[0]
import re
import sys


sys.path.append(patz)
sys.path.append('')
# print("PATH: ", sys.path)
from guiscrcpy.__main__ import launch_main
launch_main()
