#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import guiscrcpy
patz = list(guiscrcpy.__path__)[0]
import sys


sys.path.append(patz)
sys.path.append('')
# print("PATH: ", sys.path)
from guiscrcpy.launcher import bootstrap
bootstrap()
