#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from guiscrcpy.launcher import bootstrap
import sys
import guiscrcpy
patz = list(guiscrcpy.__path__)[0]


sys.path.append(patz)
sys.path.append('')
# print("PATH: ", sys.path)
bootstrap()
